name: Tag new versions on main

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  autotag:
    name: Detect and Tag New Version
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Install toml-cli
      run: cargo install toml-cli
    - uses: salsify/action-detect-and-tag-new-version@a0b3ff15a335acf6bf9e8db27036ea642561e43a
      with:
        version-command: |
          toml get ./Cargo.toml package.version | tr -d '"'
